import type { ProjectRecord } from "./types";

const editorialPlaceholder =
  "Editorial detail needed before this case study can be published.";

export const projectRecords: ProjectRecord[] = [
  {
    editorialStatus: "published",
    slug: "digicask",
    title: "DigiCask",
    featured: true,
    useVideo: false,
    videoUrl: null,
    summary: "A publicly launched investment platform where customers discover, purchase, and track fractional ownership in premium whisky casks.",
    stack: ["Next.js", "TypeScript", "Server Actions", "Zustand"],
    liveUrl: "https://www.digicask.co/",
    repoUrl: null,
    status: "shipped",
    role: "Frontend developer",
    problem: [
      "Whisky-cask investment can have a high barrier to entry and an ownership process that is difficult for newcomers to understand. DigiCask gives customers a guided path from discovering fractional investments to purchasing shares and monitoring a portfolio.",
    ],
    constraints: [
      "The customer-facing frontend had to integrate with an existing backend spanning authentication, products, orders, billing, and portfolio data while remaining polished and responsive.",
    ],
    decisions: [
      "Used Next.js server actions for backend integration so product and account workflows could remain close to the application while avoiding unnecessary client-side request plumbing.",
      "Used Zustand for focused cart state instead of introducing a heavier global-state layer.",
      "Built reusable responsive components across landing pages, authentication, checkout, dashboards, tables, charts, navigation, and policy pages to balance delivery speed with maintainability.",
    ],
    outcome: [
      "Launched publicly as DigiCask Finance, enabling customers to discover whisky investments, create accounts, purchase cask shares, and monitor their portfolios.",
    ],
    screenshots: [],
  },
  {
    editorialStatus: "published",
    slug: "nlp-examination-system",
    title: "NLP Examination System",
    featured: true,
    useVideo: false,
    videoUrl: null,
    summary: "A computer-based testing platform for creating, taking, automatically grading, and reviewing timed examinations.",
    stack: ["Next.js", "NestJS", "TypeScript", "MySQL", "AI Integration"],
    liveUrl: "https://nlp-exam-frontend.vercel.app/",
    repoUrl: null,
    status: "in-progress",
    role: "Full-stack developer",
    problem: [
      "Administrators need to create and manage examinations efficiently, while students need a reliable timed testing experience and a clear way to review results.",
    ],
    constraints: [
      "The platform had to support multiple question formats, including automated assessment of theory answers, without compromising the reliability of exam timing, submission, grading, and result reporting.",
    ],
    decisions: [
      "Separated the Next.js interface from the NestJS API to keep presentation concerns independent from authentication, examination rules, grading, and persistence.",
      "Designed distinct role-based experiences for administrators and students so each workflow exposes only the tools and information its users need.",
      "Added AI-assisted theory grading to reduce manual assessment work, accepting that model accuracy and external-service availability require careful handling and human oversight.",
    ],
    outcome: [
      "Built an end-to-end workflow covering authentication, question banks, exam management, timed test-taking, automated grading, and result reporting. The platform remains under development.",
    ],
    screenshots: [
      {
        src: "/projects/nlp-exam.webp",
        alt: "NLP Examination System landing page with a student illustration and links to log in or sign up",
        width: 1200,
        height: 800,
      },
    ],
  },
  {
    editorialStatus: "published",
    slug: "online-journal-system",
    title: "Online Journal System",
    featured: false,
    useVideo: false,
    videoUrl: null,
    summary: "A publishing platform that takes academic papers from author submission through editorial review, issue management, and publication.",
    stack: ["Next.js", "NestJS", "TypeORM", "MySQL", "Hugging Face"],
    liveUrl: "https://ojs-frontend.vercel.app/",
    repoUrl: null,
    status: "archived",
    role: "Sole full-stack developer",
    problem: [
      "Authors need to submit papers, editors need to coordinate reviews, contributors, issues, and publication, and readers need a clear way to browse published journals and articles.",
    ],
    constraints: [
      "A multi-role editorial workflow had to remain consistent while coordinating relational publishing data, authentication, file storage, PDF processing, and an external AI service.",
    ],
    decisions: [
      "Separated the Next.js frontend from a structured NestJS API so the multi-role interface and publishing rules could evolve independently.",
      "Used TypeORM with MySQL to model the relationships among users, submissions, journals, issues, contributors, and publication records.",
      "Added Hugging Face-assisted paper summaries to help editors assess submissions faster, accepting external-service dependency and the need to treat generated summaries as assistance rather than editorial judgment.",
    ],
    outcome: [
      "Produced a working end-to-end publishing workflow spanning authentication, role-based dashboards, submissions, PDF uploads, journal and issue management, AI-assisted summaries, and publication. It reduced manual administration, although public adoption metrics were not recorded.",
    ],
    screenshots: [
      {
        src: "/projects/online-journal.webp",
        alt: "Online Journal System landing page presenting its publishing workflow and AI-assisted features",
        width: 1200,
        height: 800,
      },
    ],
  },
  {
    editorialStatus: "published",
    slug: "tailpoint",
    title: "Tailpoint",
    featured: true,
    useVideo: false,
    videoUrl: null,
    summary: "A multi-tenant work-management platform that brings projects, communication, automation, and AI-assisted productivity into one governed workspace.",
    stack: ["Next.js", "NestJS", "TypeScript", "Node.js"],
    liveUrl: "https://tailpoint.vercel.app/",
    repoUrl: null,
    status: "in-progress",
    role: "Lead full-stack developer",
    problem: [
      "Teams often coordinate projects, recurring work, approvals, discussions, documents, and incoming requests across disconnected tools. Tailpoint brings those workflows into a shared, multi-tenant workspace for organization members, project collaborators, administrators, and platform operators.",
      "The platform also provides a public Node.js SDK for developers to send operational events into controlled task and automation workflows.",
    ],
    constraints: [
      "The central challenge was expanding an existing application without weakening tenant isolation or creating inconsistent permissions across the customer workspace, backend API, and operator console.",
      "Every feature had to respect organization boundaries, project roles, subscription entitlements, audit requirements, and existing workflows. External ingestion and automation also had to remain safe under retries so repeated events could not create duplicate tasks or actions.",
    ],
    decisions: [
      "Centralized feature entitlements into one capability system combining subscription plans, organization overrides, user permissions, and rollout flags. This kept access rules consistent across features, with the trade-off of additional backend and administration complexity.",
      "Kept authorization, workflow transitions, automation execution, and tenant isolation in the NestJS API instead of relying on frontend checks. The result is a safer rule set that can serve multiple clients, at the cost of more API design and testing.",
      "Designed event ingestion and automation around idempotency using stable event identifiers, deduplication keys, immutable rule versions, bounded execution chains, and retry-safe actions. This reduces duplicate work and automation loops while requiring more persistence and execution infrastructure.",
    ],
    outcome: [
      "Tailpoint now works end to end across its customer workspace, backend, operator console, and public SDK. Its completed foundation supports project planning, recurring work, structured updates, approvals, request intake, external events, and automated task actions.",
      "Development validation included 63 focused Phase 1 tests, 11 backend smoke tests, successful TypeScript checks across all three applications, applied database migrations, and a controlled pilot enabled through audited feature overrides.",
      "The product remains in active development: its Phase 1 foundation is validated, while production-rollout verification and later roadmap work continue.",
    ],
    screenshots: [
      {
        src: "/projects/tailpoint.webp",
        alt: "Tailpoint landing page showing its project workspace and project-tracking dashboard",
        width: 1200,
        height: 800,
      }
    ],
  },
  {
    editorialStatus: "published",
    slug: "tailpoint-sdk",
    title: "Tailpoint SDK",
    featured: true,
    useVideo: false,
    videoUrl: null,
    summary: "A public Node.js SDK for sending operational events into Tailpoint's governed task-intake and automation workflows.",
    stack: ["Node.js", "TypeScript", "SDK Design", "Event Ingestion"],
    liveUrl: "https://www.npmjs.com/package/@peegee/tailpoint-sdk",
    repoUrl: "https://www.npmjs.com/package/@peegee/tailpoint-sdk",
    status: "in-progress",
    role: "Lead developer",
    problem: [
      "Developers and external systems need a small, predictable integration surface for turning operational events into work inside Tailpoint without coupling directly to the platform's internal API.",
    ],
    constraints: [
      "The SDK had to preserve tenant and permission boundaries while remaining safe under network retries. Repeated delivery of the same event could not create duplicate tasks or trigger the same automation chain more than once.",
    ],
    decisions: [
      "Used stable event identifiers and deduplication keys to make ingestion retry-safe rather than expecting every caller or network request to behave exactly once.",
      "Kept the public SDK focused on the external ingestion contract while authorization, workflow rules, and tenant isolation remained enforced by Tailpoint's backend.",
      "Designed the integration around governed, bounded automation execution so incoming events cannot create uncontrolled action loops.",
    ],
    outcome: [
      "The SDK provides a reusable developer-facing entry point for universal task intake and connects external operational events to Tailpoint's controlled automation system.",
      "It is part of Tailpoint's validated Phase 1 foundation and remains under active development alongside the main platform.",
    ],
    screenshots: [],
  },
  {
    editorialStatus: "published",
    slug: "tasty-app",
    title: "Tasty App",
    featured: false,
    useVideo: false,
    videoUrl: null,
    summary: "A responsive crypto-gaming platform combining betting, wallet operations, identity verification, bonuses, and account management.",
    stack: ["Next.js", "TypeScript", "Apollo Client", "GraphQL", "Zustand", "Web3"],
    liveUrl: null,
    repoUrl: null,
    status: "in-progress",
    role: "Frontend developer",
    problem: [
      "Crypto bettors need one coherent interface for discovering and playing games while managing authentication, funds, identity verification, bonuses, communication, and account settings.",
    ],
    constraints: [
      "The frontend had to integrate with an existing GraphQL and Web3 backend while keeping complex betting, wallet, and account workflows responsive and consistent across mobile and desktop layouts.",
    ],
    decisions: [
      "Used Next.js and TypeScript to give the growing interface a structured, type-safe foundation across routes, components, and integration boundaries.",
      "Used Apollo Client for GraphQL data and server-state coordination, while Zustand handled smaller pieces of local UI state. This kept responsibilities clearer at the cost of a larger dependency and state-management surface.",
      "Built reusable responsive patterns across authentication, cashier, KYC, dashboards, charts, bonuses, settings, chat, and four game experiences instead of treating mobile as a separate interface.",
    ],
    outcome: [
      "The frontend now supports an end-to-end journey from authentication and identity checks through wallet funding, gameplay, betting, and account management across mobile and desktop.",
      "The product remains in active development.",
    ],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "techblog",
    title: "TechBlog",
    featured: false,
    summary: "A technology-blog application built with Django.",
    stack: ["Python", "Django"],
    liveUrl: null,
    repoUrl: "https://github.com/PEeGEe21/techblog",
    status: null,
    role: null,
    problem: [editorialPlaceholder],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "digi-oracle",
    title: "Digi Oracle",
    featured: false,
    summary: "A website for a modular blockchain oracle that connects Web3 applications to real-world data and events.",
    stack: ["Next.js"],
    liveUrl: "https://digioracle.vercel.app/",
    repoUrl: null,
    status: "shipped",
    role: null,
    problem: ["Web3 applications need a secure way to consume off-chain data in formats that smart contracts can use."],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "v-oracle",
    title: "V-Oracle",
    featured: false,
    summary: "A frontend website built with semantic HTML, CSS, and JavaScript.",
    stack: ["HTML", "CSS", "JavaScript"],
    liveUrl: "https://v-oracle.vercel.app/",
    repoUrl: null,
    status: "shipped",
    role: null,
    problem: [editorialPlaceholder],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "published",
    slug: "hotelos",
    title: "HotelOS",
    featured: true,
    useVideo: false,
    videoUrl: null,
    summary: "A full-stack hotel-management platform that consolidates reservations, guest services, operations, finance, staff, and reporting.",
    stack: ["Next.js", "NestJS", "TypeScript", "PostgreSQL", "BullMQ"],
    liveUrl: null,
    repoUrl: null,
    status: "in-progress",
    role: "Sole full-stack developer",
    problem: [
      "Hotel administrators and operational teams need to coordinate reservations, guests, rooms, point of sale, housekeeping, facilities, inventory, finance, staff, and reporting without relying on fragmented systems and manual handoffs.",
    ],
    constraints: [
      "Many hotel workflows affect one another in real time. The platform had to coordinate those dependencies while preserving tenant isolation, permission security, mobile usability, and consistent operational state across departments.",
    ],
    decisions: [
      "Used a TypeScript monorepo so the Next.js dashboard and NestJS API could share contracts and reduce drift at integration boundaries.",
      "Used BullMQ for background jobs that require reliable execution outside the request-response cycle, accepting additional queue and worker infrastructure in exchange for retry and processing control.",
      "Made roles, permissions, and dashboard behavior database-driven so different hotel operations can be configured without hardcoding every variation. This adds data-model complexity but keeps the product adaptable.",
    ],
    outcome: [
      "Built a near-production-ready platform spanning the dashboard, API, PostgreSQL data layer, role-based access control, real-time updates, background jobs, notifications, exports, and the core operational modules.",
      "HotelOS consolidates workflows that would otherwise require separate tools or manual coordination and provides a foundation for real-time work across hotel departments. Deployment preparation and final production validation remain in progress.",
    ],
    screenshots: [],
  },
  {
    editorialStatus: "published",
    slug: "thrustpad-finance",
    title: "Thrustpad",
    featured: true,
    useVideo: false,
    videoUrl: null,
    summary: "A Web3 launchpad for creating tokens and running fair launches, airdrops, staking campaigns, and token locks on EDU Chain.",
    stack: ["Next.js", "TypeScript", "RainbowKit", "Wagmi", "Ethers.js", "Web3"],
    liveUrl: "https://app.thrustpad.finance/",
    repoUrl: null,
    status: "in-progress",
    role: "Frontend/Web3 developer",
    problem: [
      "Project owners need an interface for creating tokens and managing launches, airdrops, staking, and token locks, while investors need a clear way to discover launches and participate through their wallets.",
    ],
    constraints: [
      "Multi-step financial workflows had to coordinate wallet connections and smart-contract transactions while making pending, successful, rejected, and failed states understandable across desktop and mobile.",
    ],
    decisions: [
      "Used Next.js to structure a responsive dashboard and the related token, launch, staking, lock, and airdrop workflows.",
      "Used RainbowKit and Wagmi for wallet compatibility and connection state, trading additional dependencies for established wallet-integration patterns.",
      "Used Ethers.js for EDU Chain contract calls and surfaced explicit transaction feedback through forms and modals so on-chain wait states did not appear as an unresponsive interface.",
    ],
    outcome: [
      "Delivered a functional EDU Chain launchpad interface with on-chain token creation and the foundations for managing launches, locks, staking campaigns, and airdrops. The product remains in active development.",
    ],
    screenshots: [],
  },
];
