import type { ProjectRecord } from "./types";

const editorialPlaceholder =
  "Editorial detail needed before this case study can be published.";

export const projectRecords: ProjectRecord[] = [
  {
    editorialStatus: "draft",
    slug: "thrustpad-finance",
    title: "Thrustpad Finance",
    summary: "A launchpad interface for discovering and participating in token launches.",
    stack: ["Next.js"],
    liveUrl: "https://app.thrustpad.finance/",
    repoUrl: null,
    status: null,
    role: null,
    problem: ["The public product presents token launches and their participation details."],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "digicask",
    title: "DigiCask",
    summary: "A platform that makes whisky-cask investment more accessible through fractional, blockchain-recorded ownership.",
    stack: ["Next.js"],
    liveUrl: "https://www.digicask.co/",
    repoUrl: null,
    status: null,
    role: null,
    problem: ["Whisky-cask investment has a high barrier to entry and an ownership process that can be difficult for newcomers to understand."],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "nlp-examination-system",
    title: "NLP Examination System",
    summary: "A web-based examination system built with a Next.js frontend and NestJS backend.",
    stack: ["Next.js", "NestJS"],
    liveUrl: "https://nlp-exam-frontend.vercel.app/",
    repoUrl: null,
    status: null,
    role: null,
    problem: [editorialPlaceholder],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "open-journal-system",
    title: "Open Journal System",
    summary: "A web application for managing an academic-journal workflow.",
    stack: ["Next.js", "NestJS"],
    liveUrl: "https://ojs-frontend.vercel.app/",
    repoUrl: null,
    status: null,
    role: null,
    problem: [editorialPlaceholder],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "tailpoint",
    title: "Tailpoint",
    summary: "A full-stack application built with Next.js and NestJS.",
    stack: ["Next.js", "NestJS"],
    liveUrl: "https://tailpoint.vercel.app/",
    repoUrl: null,
    status: null,
    role: null,
    problem: [editorialPlaceholder],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "techblog",
    title: "TechBlog",
    summary: "A technology-blog application built with Django.",
    stack: ["Python", "Django"],
    liveUrl: null,
    repoUrl: "https://github.com/PEeGEe21/techblog",
    status: null,
    role: null,
    problem: [editorialPlaceholder],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "digi-oracle",
    title: "Digi Oracle",
    summary: "A website for a modular blockchain oracle that connects Web3 applications to real-world data and events.",
    stack: ["Next.js"],
    liveUrl: "https://digioracle.vercel.app/",
    repoUrl: null,
    status: null,
    role: null,
    problem: ["Web3 applications need a secure way to consume off-chain data in formats that smart contracts can use."],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "v-oracle",
    title: "V-Oracle",
    summary: "A frontend website built with semantic HTML, CSS, and JavaScript.",
    stack: ["HTML", "CSS", "JavaScript"],
    liveUrl: "https://v-oracle.vercel.app/",
    repoUrl: null,
    status: null,
    role: null,
    problem: [editorialPlaceholder],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
  {
    editorialStatus: "draft",
    slug: "hotelos",
    title: "HotelOS",
    summary: "A hotel-operations project awaiting final case-study details.",
    stack: [],
    liveUrl: null,
    repoUrl: null,
    status: null,
    role: null,
    problem: [editorialPlaceholder],
    constraints: [editorialPlaceholder],
    decisions: [editorialPlaceholder],
    outcome: [editorialPlaceholder],
    screenshots: [],
  },
];
